from maderapp.model.timber_clasification_efficientNet import TimberEfficientNet
from maderapp.model.timber_clasification_efficientNetNS import TimberEfficientNetNS
from maderapp.model.timber_clasification_resNet import TimberResNet
from maderapp.model.timber_clasification_mobileNet import TimberMobileNet
